[package]
name = "tiny-ecs"
authors = ["libkluid <kluid.me@yahoo.com>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
